version: '3.8'

services:
  evershelf:
    build: .
    container_name: evershelf
    restart: unless-stopped
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.paperless.rule=Host(`gnamme.marcodalli.net`)
        - traefik.http.services.paperless.loadbalancer.server.port=80
        - traefik.http.routers.paperless.entrypoints=https
        - traefik.http.routers.paperless.tls=true
        - traefik.http.routers.paperless.tls.certresolver=le 
    volumes:
      - type: bind
        source: "/mnt/gluster-vol1/evershelf/evershelf_data"
        target: "/var/www/html/data"
      # Mount your local .env configuration
      - ./.env:/var/www/html/.env:ro
    environment:
      - TZ=Europe/Rome

networks:
  traefik-public:
    external: true
